config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  resources :articles do
    resources :comments
  end
  resources :categories
  resources :users

  root 'articles#index'

end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id           :integer          not null, primary key
#  title        :string
#  body         :text
#  published_at :datetime
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  excerpt      :string
#  location     :string
#  user_id      :integer
#
class Article < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :categories
  has_many :comments

  validates :title, presence: true, uniqueness: true
  validates :body, presence: true

  scope :published, -> { where.not(published_at: nil) }
  scope :draft, -> { where(published_at: nil) }
  scope :recent, -> { published.where('articles.published_at > ?', 1.week.ago.to_date) }

  searchable do
    text :title, boost: 3
    text :excerpt, :body
    time :updated_at
  end

  def published?
    published_at.present?
  end

  def owned_by?(owner)
    return false unless owner.is_a?(User)
    user == owner
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource

  def index
    @search = Article.search do
      fulltext params[:search][:query] if params[:search]
      paginate page: params[:page], per_page: 10
      order_by(:updated_at, :desc)
    end
    @articles = @search.results
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = current_user.articles.build(article_params)
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :location, :excerpt, :body,
                                    :published_at, category_ids: [])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<%= div_for article do %>
	<article class="uk-article uk-margin-bottom">
  <span class="uk-link-muted uk-float-right">
    <% if can? [:update, :destroy], @article %>
    <%= link_to edit_article_path(@article) do %>
    <i class="uk-icon-pencil"></i>
    <% end %>
    <span> | </span>
        <%= link_to @article, method: :delete, data: { confirm: 'Are you sure?' } do %>
    <i class="uk-icon-trash"></i>
        <% end %>
          <% end %>
          </span>
            <span class="uk-article-title"><%= article.title %></span>

    <p class="uk-article-meta">
                <i class="uk-icon-clock-o"></i>
                <%= distance_of_time_in_words_to_now(article.published_at) %>
                ago
            </p>
    <p class="uk-article-lead"><%= @article.excerpt %></p>
    <hr class="uk-article-divider">
</article>
    <%= article.body.html_safe  %>
    <span class="uk-float-right">
    <% @article.categories.each do |category|%>
    <span class="uk-badge" ><%= category.name %></span>
    <% end %>
    </span>
<% end %>

app/views/articles/_form.html.erb
<%= form_for @article, :html => {:class => 'uk-form'} do |f| %>
<% if @article.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

  <ul>
    <% @article.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<form class="uk-form data-no-turbolink">
<div class="uk-form-row">
  <%= f.text_field :title, :class => "uk-width-1-1", :placeholder => "Title"%>
</div>
<div class="uk-form-row">
  <%= f.text_area :body, :class => "ckeditor", :id =>"body", :rows => "50" %>
</div>
<div class="uk-form-row">
  <%= f.text_area :excerpt, :class =>"uk-width-1-1", :rows => "3", :placeholder => "Excerpt" %>
</div>
<div class="uk-form-row">
  <%= f.text_field :location, :class =>"uk-width-1-1", :placeholder => "Location" %>
</div>
<div class="uk-form-row">
  <%= f.label "Categories" %><br />
<%= select_tag "article[category_ids][]", options_from_collection_for_select(Category.all, "id", "name", @article.categories.ids), class: "select2", multiple: "multiple",  style: "width: 100%"%>
</div>
<div class="uk-form-row">
  <%= f.label :published_at %><br>
  <%= f.datetime_select :published_at%>

</div>
<div class="uk-form-row">
  <%= f.submit class: 'uk-button'%>
</div>
</form>
<% end %>

app/views/articles/_search.html.erb
<%= form_tag(articles_path,  method: "get", remote: true, class: "uk-form uk-margin-remove uk-display-inline-block") do %>
<div class="uk-input-group">
	<input type="text" name="search[query]" placeholder="Type and press Enter...">
</div>
<% end %>

app/views/articles/edit.html.erb
<%= render 'form' %>
<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>
</div>

app/views/articles/index.html.erb
<div class="articles">
  <%= 'No results found...' if @articles.blank? %>
  <% @articles.each do |article| %>

  <div class="uk-article">
    <h3 class="uk-article-title"><%= article.title %></h3>
    <div class="uk-article-meta">
      <i class="uk-icon-clock-o"></i>
      <%= distance_of_time_in_words_to_now(article.published_at) %>
      ago
    </div>

    <div class="uk-article-lead">
      <%= article.excerpt %>
    </div>
    <div><%= link_to article do %>
      <i class="uk-icon-expand"> Read more...</i>
      <% end %>
    </div>
    <hr class="uk-article-divider">

  </div>
  <br>
  <% end %>
  <%= paginate @articles %>
</div>

app/views/articles/index.js.erb
$(".articles").html("<%= escape_javascript render template: "articles/index.html.erb" %>");

app/views/articles/new.html.erb
<div class="container">
	<h1>New Article</h1>
	<%= render 'form' %>
	<%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<%= render @article %>
<br>
<h3>Comments</h3>
<div id="comments">
  <%= render @article.comments %>
</div>
<%= render :file => 'comments/new',:remote => true %>