config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  resources :articles do
    resources :comments
  end
  resources :categories
  resources :users

  root 'articles#index'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string
#  hashed_password        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  role_id                :integer
#
require 'digest'
class User < ActiveRecord::Base
  has_one :profile
  belongs_to :role
  has_many :articles, -> { order('published_at DESC, title ASC') }, dependent: :nullify
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  before_create :set_default_role

  def self.search(query)
    query.delete_if { |_k, v| v.blank? }
    if query.key?(:email)
      where('email ILIKE ?', "%#{query['email']}%")
    else
      all
    end
  end

  ROLES = %w(admin moderator user banned)
  ROLES.each do |role|
    define_method("#{role}?") do
      role_name == role
    end
  end

  def setting_access?
    admin? || moderator?
  end

  def role_name
    role.name if role
  end

  private

  def set_default_role
    self.role ||= Role.find_by_name('user')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  load_and_authorize_resource

  def index
    if search_params
      @users = User.search(search_params)
    else
      @users = User.order(updated_at: :DESC).includes(:role)
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to users_path, notice: 'Updated user information successfully.'
    else
      render action: 'edit'
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :role_id).delete_if { |_k, v| v.empty? }
  end

  def search_params
    params.require(:search).permit(:email) if params[:search]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, :html => {:class => 'uk-form'}  do |f| %>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %>
prohibited this user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <div class="uk-form-row">
  <%= f.text_field :email, :class => "uk-width-1-1", :placeholder => "Email"%>
  </div>
    <div class="uk-form-row">
  <%= select_tag "user[role_id]", options_from_collection_for_select(Role.all, "id", "name", @user.role_id), class: "select2",  style: "width: 100%"%>
</div>
   <div class="uk-form-row">
      <%= f.password_field :password, :class => "uk-width-1-1", :placeholder => "Password"%>
  </div>
  <div class="uk-form-row">
      <%= f.password_field :password, :class => "uk-width-1-1", :placeholder => "Password confirmation"%>
  </div>
   <div class="uk-form-row">
    <%= f.submit class: 'uk-button'%>
  </div>
<% end %>

app/views/users/_search.html.erb
<%= form_tag(users_path,  method: "get", class: "uk-form") do %>
    <div class="uk-form-row">
      <input type="text" name="search[email]" placeholder="Email">
      <%= submit_tag("Search", class: "uk-button") %>
    </div>
  <% end %>

app/views/users/edit.html.erb
<h1>New user</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>
<%= render 'search' %>
<table class="uk-table uk-link-muted uk-width-small">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
      <td ><%= user.email.capitalize %></td>
      <td ><%= user.role.name.capitalize %></td>
      <td >
        <%= link_to '', edit_user_path(user), class: "uk-icon-pencil" %>
        <span> | </span>
        <%= link_to '', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "uk-icon-trash" %>

      </td>
      </tr>
    <% end %>
  </tbody>
</table>