config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  resources :articles do
    resources :comments
  end
  resources :categories
  resources :users

  root 'articles#index'

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Category < ActiveRecord::Base
  has_and_belongs_to_many :articles

  validates :name, presence: true, uniqueness: true

  def self.search(query)
    query.delete_if { |_k, v| v.blank? }
    if query.key?(:name)
      where('name ILIKE ?', "%#{query['name']}%")
    else
      all
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource

  def index
    if search_params
      @categories = Category.search(search_params)
    else
      @categories = Category.all
    end
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { redirect_to categories_url }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def search_params
    params.require(:search).permit(:name) if params[:search]
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, :html => {:class => 'uk-form'}  do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="uk-form-row">
  <%= f.text_field :name, :class => "uk-width-1-1", :placeholder => "Name"%>
  </div>
<div class="uk-form-row">
  <%= f.submit class: 'uk-button'%>
</div>
<% end %>

app/views/categories/_new.html.erb
<h1>New Category</h1>

<%= form_tag(categories_path,  method: "post", class: "uk-form") do %>
      <div class="uk-form-row">
  		<input type="text" name="category[name]" placeholder="Title" class="uk-width-1-2">
  </div>
  <div class="uk-form-row">
  <%= submit_tag("Create", class: "uk-button") %>
  </div>
  <% end %>

app/views/categories/_search.html.erb
<%= form_tag(categories_path,  method: "get", class: "uk-form") do %>
    <div class="uk-form-row">
      <input type="text" name="search[name]" placeholder="Name">
      <%= submit_tag("Search", class: "uk-button") %>
    </div>
  <% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<%= render 'new' %>
<h1>Listing Categories</h1>
<%= render 'search' %>
<table class="uk-table uk-link-muted uk-width-small">
  <thead>
    <tr>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
      <td ><%= category.name %></td>
      <td >
        <%= link_to '', edit_category_path(category), class: "uk-icon-pencil" %>
        <span> | </span>
        <%= link_to '', category, method: :delete, data: { confirm: 'Are you sure?' }, class: "uk-icon-trash" %>

      </td>
      </tr>
    <% end %>
  </tbody>
</table>