config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  resources :articles do
    resources :comments
  end
  resources :categories
  resources :users

  root 'articles#index'

end

app/views/layouts/_messages.html.erb
<%if notice.present?%>
<div class="uk-alert uk-alert-success" data-uk-alert>
    <a href="" class="uk-alert-close uk-close"></a>
    <%= notice %>
</div>
<% elsif alert.present? %>
<div class="uk-alert uk-alert-warning" data-uk-alert>
    <a href="" class="uk-alert-close uk-close"></a>
    <%= alert %>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="uk-navbar" data-uk-sticky>
  <div class="uk-navbar-brand">BLOG</div>
  <ul class="uk-navbar-nav">
    <li class="uk-active"><a href=<%=root_path%>><i class="uk-icon-home uk-icon-medium"></i></a></li>
    <li class="uk-parent"><a href=<%= new_article_path %> data-no-turbolink>CREATE</a></li>
  </ul>
  <!-- <div class="uk-navbar-content"><a href="">CREATE</a></div> -->
  <div class="uk-navbar-flip">

    <ul class="uk-navbar-nav">
      <%if current_user%>
      <li class="uk-navbar-content uk-hidden-small"><%= render partial: 'articles/search' %></li>
      <% if current_user.setting_access?%>
      <li class="uk-parent" data-uk-dropdown="{mode:'click'}"><a href=""><i class="uk-icon-cog uk-icon-medium"></i></a>
        <div class="uk-dropdown uk-dropdown-navbar">
          <ul class="uk-nav uk-nav-navbar">
          <% if current_user.admin?%>
            <li>
              <%= link_to users_path do %>
              <i class="uk-icon-users"> Users</i>
              <% end %>
            </li>
            <% end %>
            <li>
              <%= link_to categories_path do %>
              <i class="uk-icon-tags"> Categories</i>
              <% end %>
            </li>
          </ul>
        </div>
      </li>
      <% end %>
      <li class="uk-parent" data-uk-dropdown="{mode:'click'}"><a href=""><i class="uk-icon-bars uk-icon-medium"></i></a>
        <div class="uk-dropdown uk-dropdown-navbar">
          <ul class="uk-nav uk-nav-navbar">
            <li class="uk-nav-header"><%= current_user.email %></li>
            <li class="uk-nav-divider"></li>
            <li>
              <%= link_to root_path do %>
              <i class="uk-icon-user"> Profile</i>
              <% end %>
            </li>
          </ul>
          <ul class="uk-nav uk-nav-navbar">
            <li>
              <%= link_to destroy_user_session_path, :method => :delete do %>
              <i class="uk-icon-sign-out"> Logout</i>
              <% end %>
            </li>
          </ul>
        </div>
      </li>

      <%else%>
      <li class="uk-parent" data-uk-dropdown="{mode:'click'}"><a href=""><i class="uk-icon-bars uk-icon-medium"></i></a>
        <div class="uk-dropdown uk-dropdown-navbar">
          <ul class="uk-nav uk-nav-navbar">
            <li>
              <%= link_to new_user_session_path  do %>
              <i class="uk-icon-sign-in"> Login</i>
              <% end %>
            </li>
          </ul>
        </div>
      </li>
      <% end%>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<%= render partial: 'layouts/navbar' %>
<body>
  <div class="uk-width-7-10 uk-container-center uk-margin-top">
  <%= render partial: 'layouts/messages' %>
    <%= yield %>
  </div>
</body>
</html>